// auth
export const SAVE_USER_DATA = "SAVE_USER_DATA";

// case loading
export const CASE_LOADING = "CASE_LOADING";
export const ALERT_STATUS = "ALERT_STATUS";

// room
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOM_DETAIL_SUCCESS = "FETCH_ROOM_DETAIL_SUCCESS";
export const FETCH_USER_JOINED_ROOM = "FETCH_USER_JOINED_ROOM";

// users
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
